-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 08:57:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pm` ;

-- -----------------------------------------------------
-- Table `pm`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pm`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`country` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pm`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`person` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdentityNumber` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `FirstName` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `LastName` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Email` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Phone` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Gender` INT NULL DEFAULT NULL,
  `Description` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pm`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`address` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PersonId` INT NOT NULL,
  `CountryId` INT NOT NULL,
  `Street` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `City` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ZIP` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Address_CountryId` (`CountryId` ASC) VISIBLE,
  INDEX `IX_Address_PersonId` (`PersonId` ASC) VISIBLE,
  CONSTRAINT `FK_Address_Country_CountryId`
    FOREIGN KEY (`CountryId`)
    REFERENCES `pm`.`country` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Address_Person_PersonId`
    FOREIGN KEY (`PersonId`)
    REFERENCES `pm`.`person` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pm`.`taxnumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`taxnumber` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PersonId` INT NOT NULL,
  `CountryId` INT NOT NULL,
  `Number` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_TaxNumber_CountryId` (`CountryId` ASC) VISIBLE,
  INDEX `IX_TaxNumber_PersonId` (`PersonId` ASC) VISIBLE,
  CONSTRAINT `FK_TaxNumber_Country_CountryId`
    FOREIGN KEY (`CountryId`)
    REFERENCES `pm`.`country` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_TaxNumber_Person_PersonId`
    FOREIGN KEY (`PersonId`)
    REFERENCES `pm`.`person` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
